# Generated by Django 5.0.7 on 2024-09-02 23:42

import django.core.validators
import django.db.models.deletion
import producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), producto.models.validate_image_size])),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s')], default='Unidades', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('habilitar_venta', models.BooleanField(default=True)),
                ('habilitar_stock', models.BooleanField(default=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.categoria')),
                ('sub_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('motivo', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s')], default='Unidades', max_length=50)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_manual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
            options={
                'verbose_name': 'precio',
                'verbose_name_plural': 'Precio de Productos',
            },
        ),
    ]
