# Generated by Django 4.0.1 on 2024-12-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar',
            field=models.BooleanField(default=False, help_text='Mostrar en la carta al publico (Carta QR)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Compuesto', 'Compuesto')], default='Simple', max_length=10),
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s')], max_length=50)),
                ('producto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='producto.producto')),
                ('producto_usado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='producto.producto')),
            ],
            options={
                'verbose_name': 'composicion',
                'verbose_name_plural': '🛠️ Composicion',
            },
        ),
    ]
