# Generated by Django 4.0.1 on 2024-12-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_mostrar_producto_tipo_recetaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetaproducto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s')], default='Unidades', max_length=50),
        ),
    ]
