# Generated by Django 5.0 on 2025-02-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_recetaproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=100, null=True),
        ),
    ]
