# Generated by Django 5.0.11 on 2025-02-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt²s')], default='Unidades', max_length=50),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt²s')], default='Unidades', max_length=50),
        ),
        migrations.AlterField(
            model_name='recetaproducto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt²s')], default='Unidades', max_length=50),
        ),
    ]
