# Generated by Django 5.0.11 on 2025-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_producto_unidad_de_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, null=True, unique=True),
        ),
    ]
