# Generated by Django 5.0.7 on 2024-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='stock_negativo_ldp',
            field=models.BooleanField(default=False, verbose_name='Filtrar productos con Stock negativo de la tienda'),
        ),
    ]
