# Generated by Django 5.0 on 2024-09-19 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_configuracion_stock_negativo_ldp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_user_assignment'),
        ),
    ]
