# Generated by Django 4.0.1 on 2024-12-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_asignacion_unique_user_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='stock_negativo_ldp',
            field=models.BooleanField(default=True, verbose_name='Filtrar productos con Stock negativo de la tienda'),
        ),
    ]
