# Generated by Django 4.0.1 on 2024-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodecompra',
            name='Nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo para el método de pago que usarás para pagar las compras a proveedores.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mediodecompra',
            name='cuenta_corriente',
            field=models.BooleanField(default=False, help_text='Esta casilla permite agrupar el medio de pago como DEUDA CON EL PROVEEDOR (Cuentas Corrientes)'),
        ),
        migrations.AlterField(
            model_name='mediodecompra',
            name='efectivo',
            field=models.BooleanField(default=False, help_text='Si usted quiere tomar el metodo de pago como efectivo (Para el cierre de caja)'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='Nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo para el método de pago que usarán los clientes para pagarte.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='cuenta_corriente',
            field=models.BooleanField(default=False, help_text='Esta casilla permite agrupar el medio de pago como DEUDA DE CLIENTES (Cuentas Corrientes)'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='efectivo',
            field=models.BooleanField(default=False, help_text='Si usted quiere tomar el metodo de pago como efectivo (Para el cierre de caja)'),
        ),
    ]
