# Generated by Django 4.0.1 on 2024-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_configuracion_mostrar_productos_cocina_ldp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
