# Generated by Django 4.0.1 on 2024-12-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_configuracion_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='logo',
        ),
    ]
