# Generated by Django 4.0.1 on 2024-12-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_configuracion_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tiket_comandera',
            field=models.BooleanField(default=False),
        ),
    ]
