# Generated by Django 5.0 on 2025-02-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_configuracion_tiket_comandera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuario'},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'caja', 'verbose_name_plural': 'Caja'},
        ),
    ]
