# Generated by Django 5.0.11 on 2025-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_asignacion_options_alter_caja_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='contactos',
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='alias',
            field=models.CharField(blank=True, help_text='Campo para agregar entre el titulo y los productos en la venta (Dejar vacío si no se requiere)', max_length=255, null=True, verbose_name='Campo libre 1'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='cuit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo libre 2'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(blank=True, help_text='(Esta información aparecerá en el ticket de venta)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(blank=True, help_text='(Esta información aparecerá en el ticket de venta)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_cuenta',
            field=models.CharField(blank=True, help_text='Campo para agregar entre el titulo y los productos en la venta (Dejar vacío si no se requiere)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, help_text='(Esta información aparecerá en el ticket de venta)', max_length=255, null=True),
        ),
    ]
