# Generated by Django 5.0.11 on 2025-02-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_remove_configuracion_contactos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='entrega_ventas',
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Moneda',
            field=models.ForeignKey(default=1, help_text='Seleccione la moneda que desea manejar en el sistema (Puede crear una nueva)', on_delete=django.db.models.deletion.CASCADE, related_name='moneda_principal', to='agenda.monedas'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='alias',
            field=models.CharField(blank=True, help_text='Si requiere agregar una linea de texto en el ticket de venta puede usar este campo (Dejar vacío si no se requiere)', max_length=255, null=True, verbose_name='Campo libre (Segunda linea)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='cuit',
            field=models.CharField(blank=True, help_text='Si requiere agregar una linea de texto en el ticket de venta puede usar este campo (Dejar vacío si no se requiere)', max_length=255, null=True, verbose_name='Campo libre (Tercera linea)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='entrega',
            field=models.BooleanField(default=False, help_text="Esta opción agrega la acción de 'Entregar' cada venta, por lo que todas las ventas serán NO ENTREGADAS por defecto.", verbose_name='🚴🏻\u200d♂️ Gestionar Entrega'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='mostrar_foto',
            field=models.BooleanField(default=True, help_text='Si quiere que se muestren las fotos de los productos en su tienda deje esta casilla en Veradero.', verbose_name='📷 Mostrar Foto'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_cuenta',
            field=models.CharField(blank=True, help_text='Si requiere agregar una linea de texto en el ticket de venta puede usar este campo (Dejar vacío si no se requiere)', max_length=255, verbose_name='Campo libre (Primera linea)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='permitir_venta_negativa',
            field=models.BooleanField(default=True, help_text='Esta opción permite ocultar los productos con stock negativo desde la tienda', verbose_name='🏪 Ocultar productos sin Stock de la tienda'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='stock_negativo_ldp',
            field=models.BooleanField(default=True, help_text='Esta opción permite ocultar los productos con stock negativo desde la tienda', verbose_name='📄 Ocultar productos sin Stock de la Lista de precios'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='vista_clasica',
            field=models.BooleanField(default=True, help_text='Si quiere que su tienda muestre los productos en forma de tarjeta, deje en Verdadero esta casilla.', verbose_name='🖼️ Vista como Tarjetas'),
        ),
    ]
