# Generated by Django 5.0.11 on 2025-02-13 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_remove_configuracion_entrega_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='habilitar_cc',
            field=models.BooleanField(default=False, help_text="Este check habilita al cliente todos los medios de pago que sean de tipo 'Cuenta Corriente'", verbose_name='Habilitar cuenta corriente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='1111-1111', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='Moneda',
            field=models.ForeignKey(default=1, help_text='Seleccione la moneda que desea manejar en el sistema (Puede crear una nueva)', on_delete=django.db.models.deletion.CASCADE, related_name='moneda_principal', to='agenda.monedas', verbose_name='💵 Moneda'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='precio_venta_automatico',
            field=models.BooleanField(default=True, help_text='Si quiere que los precios de venta de tus productos se ingresen manualmente, deja esta casilla en True. (En Falso, los precios se calcularán en base a una % Rentabilidad)', verbose_name='🧮 Cálculo de precios'),
        ),
    ]
