# Generated by Django 5.0.11 on 2025-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_configuracion_logo_alter_configuracion_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tiket_comandera',
            field=models.BooleanField(default=False, help_text='Alterna entre ticket para impresora de calor (Comandas 80mm) o A4. (En Verdadero imprime A4)', verbose_name='🖨️ Ticket A4'),
        ),
    ]
