# Generated by Django 5.0.11 on 2025-02-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_alter_configuracion_tiket_comandera'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_decimales',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
