# Generated by Django 5.0.11 on 2025-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_configuracion_mostrar_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='mostrar_decimales',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=2, help_text='Ingrese la cantidad de decimales que desea mostrar en ticket.', max_length=10, verbose_name='🖨️ Decimales en ticket'),
        ),
    ]
