# Generated by Django 5.0.11 on 2025-02-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_alter_configuracion_mostrar_decimales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tiket_comandera',
            field=models.CharField(choices=[('A4', 'Ticket A4'), ('80mm', 'Ticket Comandera (80mm)'), ('58mm', 'Ticket 58mm')], default='80mm', help_text='Seleccione el formato del ticket para impresión: Ticket A4, Ticket Comandera (80mm) o Ticket 58mm.', max_length=255, verbose_name='🖨️ Ticket A4'),
        ),
    ]
