# Generated by Django 4.0.1 on 2024-12-14 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecaja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportemensual',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
