# Generated by Django 4.0.1 on 2024-12-14 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_mediodecompra_nombre_and_more'),
        ('reportes', '0002_alter_reportecaja_fecha_alter_reportemensual_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportecaja',
            name='cobrado_clientes',
        ),
        migrations.RemoveField(
            model_name='reportecaja',
            name='pagado_a_proveedores',
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='cobrado_clientes_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cobros de cuentas corrientes de Clientes con dinero en Efectivo', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='cobrado_clientes_otros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cobros de cuentas corrientes de Clientes en Medios de pagos Virtuales/Otros', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='pagado_proveedores_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Pagos de cuentas corrientes a Proveedores con dinero en Efectivo)', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='pagado_proveedores_otros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Pagos de cuentas corrientes a Proveedores con Medios de pagos Virtuales/Otros', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='caja',
            field=models.ForeignKey(help_text='Seleccione la caja a obtener el reporte.', on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='efectivo_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ingrese el dinero en efectivo que tiene al final del dia.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='efectivo_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ingrese el dinero efectivo inicial de la caja.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Seleccione la fecha que desea obtener el reporte.'),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='total_ventas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total de Ventas General del dia.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='total_ventas_cc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe total de vendido en Cuentas Corrientes (Deuda de clientes)', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='total_ventas_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe total de las ventas cobradas en efectivo.', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaja',
            name='total_ventas_virtuales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe total de las ventas cobradas en cuentas virtuales y otros.', max_digits=25, null=True),
        ),
    ]
