# Generated by Django 4.0.1 on 2024-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_reportecaja_cobrado_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecaja',
            name='total_compras',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total de Compras General del dia.', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='total_compras_cc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe comprado en Cuentas Corrientes (Deuda con proveedor)', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='total_compras_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe comprado en efectivo.', max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='total_compras_virtuales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Importe compradoen cuentas virtuales y otros.', max_digits=25, null=True),
        ),
    ]
