# Generated by Django 4.0.1 on 2024-12-14 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
        ('compra', '0002_pagosproveedores_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
    ]
