# Generated by Django 4.0.1 on 2024-12-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
        ('compra', '0003_compra_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
        migrations.AlterField(
            model_name='pagosproveedores',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
    ]
