# Generated by Django 5.0.11 on 2025-02-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_compra_caja_alter_pagosproveedores_caja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'compra', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterModelOptions(
            name='pagosproveedores',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'Pagos a proveedores'},
        ),
    ]
