# Generated by Django 5.0.11 on 2025-02-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_compra_options_alter_pagosproveedores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='unidades_producto',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=25),
        ),
    ]
