# Generated by Django 5.0.11 on 2025-02-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_detallecompra_unidades_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='unidad_de_medida_producto',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2', 'Mt²')], default='Unidades', max_length=50),
        ),
    ]
