# Generated by Django 5.0.11 on 2025-02-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_alter_detallecompra_unidad_de_medida_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='unidad_de_medida',
            field=models.CharField(blank=True, choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2', 'Mt²')], max_length=50, null=True),
        ),
    ]
