# Generated by Django 5.0.11 on 2025-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0010_detallecompra_costo_unitario_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2', 'Mt²')], default='Unidades', max_length=50, null=True),
        ),
    ]
