# Generated by Django 4.0.1 on 2024-12-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(default='Delicious Bites', max_length=100)),
                ('hero_title', models.CharField(default='Bienvenidos a Delicious Bites', max_length=255)),
                ('hero_description', models.TextField(default='Experiencia culinaria excepcional en cada bocado')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('about_title', models.CharField(default='Sobre Nosotros', max_length=255)),
                ('about_text1', models.TextField(default='Texto 1 sobre nosotros')),
                ('about_text2', models.TextField(default='Texto 2 sobre nosotros')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('featured_title', models.CharField(default='Platos Destacados', max_length=255)),
                ('featured_dish1_title', models.CharField(default='Plato 1', max_length=100)),
                ('featured_dish1_description', models.TextField(default='Descripción Plato 1')),
                ('featured_dish1_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('featured_dish2_title', models.CharField(default='Plato 2', max_length=100)),
                ('featured_dish2_description', models.TextField(default='Descripción Plato 2')),
                ('featured_dish2_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('featured_dish3_title', models.CharField(default='Plato 3', max_length=100)),
                ('featured_dish3_description', models.TextField(default='Descripción Plato 3')),
                ('featured_dish3_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('chef_title', models.CharField(default='Nuestro Chef', max_length=255)),
                ('chef_name', models.CharField(default='Chef [Nombre]', max_length=100)),
                ('chef_bio', models.TextField(default='Biografía del Chef')),
                ('chef_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('events_title', models.CharField(default='Eventos Especiales', max_length=255)),
                ('event1_title', models.CharField(default='Evento 1', max_length=100)),
                ('event1_description', models.TextField(default='Descripción Evento 1')),
                ('event1_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('event2_title', models.CharField(default='Evento 2', max_length=100)),
                ('event2_description', models.TextField(default='Descripción Evento 2')),
                ('event2_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('event3_title', models.CharField(default='Evento 3', max_length=100)),
                ('event3_description', models.TextField(default='Descripción Evento 3')),
                ('event3_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('gallery_title', models.CharField(default='Galería', max_length=255)),
                ('gallery_images', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('testimonials_title', models.CharField(default='Lo que dicen nuestros clientes', max_length=255)),
                ('testimonial1', models.TextField(default='Testimonio 1')),
                ('testimonial1_author', models.CharField(default='Autor Testimonio 1', max_length=100)),
                ('testimonial2', models.TextField(default='Testimonio 2')),
                ('testimonial2_author', models.CharField(default='Autor Testimonio 2', max_length=100)),
                ('testimonial3', models.TextField(default='Testimonio 3')),
                ('testimonial3_author', models.CharField(default='Autor Testimonio 3', max_length=100)),
                ('location_title', models.CharField(default='Nuestra Ubicación', max_length=255)),
                ('address', models.TextField(default='Calle Principal, 123\n[Tu Ciudad], [Código Postal]')),
                ('schedule', models.TextField(default='Lunes a Viernes: 12:00 - 22:00\nSábado y Domingo: 12:00 - 23:00')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('contact_title', models.CharField(default='Contacto', max_length=255)),
                ('contact_phone', models.CharField(default='(123) 456-7890', max_length=20)),
                ('contact_email', models.EmailField(default='contacto@deliciousbites.com', max_length=254)),
            ],
        ),
    ]
