# Generated by Django 4.0.1 on 2024-12-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_alter_landingpage_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='logo',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='logo1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
