# Generated by Django 4.0.1 on 2024-12-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0003_remove_landingpage_logo_landingpage_logo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='logo1',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
