# Generated by Django 4.0.1 on 2024-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0006_landingpage_about_color_landingpage_about_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='about_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
