# Generated by Django 4.0.1 on 2024-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0007_landingpage_about_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish1_description',
            new_name='especialidades_dish1_description',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish1_image',
            new_name='especialidades_dish1_image',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish1_title',
            new_name='especialidades_dish1_title',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish2_description',
            new_name='especialidades_dish2_description',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish2_image',
            new_name='especialidades_dish2_image',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish2_title',
            new_name='especialidades_dish2_title',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish3_description',
            new_name='especialidades_dish3_description',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish3_image',
            new_name='especialidades_dish3_image',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_dish3_title',
            new_name='especialidades_dish3_title',
        ),
        migrations.RenameField(
            model_name='landingpage',
            old_name='featured_title',
            new_name='especialidades_title',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='especialidades_bg_color',
            field=models.CharField(default='#f0f0f0', help_text='Color de fondo en formato hexadecimal (ejemplo: #f0f0f0)', max_length=7),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='especialidades_dish4_description',
            field=models.TextField(default='Descripción Plato 3'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='especialidades_dish4_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='especialidades_dish4_title',
            field=models.CharField(default='Plato 3', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='especialidades_font_color',
            field=models.CharField(default='#000000', help_text='Color del texto en formato hexadecimal (ejemplo: #000000)', max_length=7),
        ),
    ]
