# Generated by Django 4.0.1 on 2024-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0009_remove_landingpage_chef_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='testimonial1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='testimonial2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='testimonial3_logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
    ]
