# Generated by Django 4.0.1 on 2024-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0010_landingpage_testimonial1_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='contact_bg_color',
            field=models.CharField(default='#f9f9f9', help_text='Color de fondo en formato hexadecimal (ejemplo: #f9f9f9)', max_length=7),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contact_font_color',
            field=models.CharField(default='#000000', help_text='Color del texto en formato hexadecimal (ejemplo: #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='location_bg_color',
            field=models.CharField(default='#f0f0f0', help_text='Color de fondo en formato hexadecimal (ejemplo: #f0f0f0)', max_length=7),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='location_font_color',
            field=models.CharField(default='#000000', help_text='Color del texto en formato hexadecimal (ejemplo: #000000)', max_length=7),
        ),
    ]
