# Generated by Django 4.0.1 on 2024-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0012_remove_landingpage_contact_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'Landing', 'verbose_name_plural': 'Pagina web'},
        ),
        migrations.AddField(
            model_name='landingpage',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='nombre',
            field=models.CharField(default='Página de Inicio', max_length=255),
        ),
    ]
