# Generated by Django 5.0.7 on 2024-09-02 23:42

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('detalles', models.TextField()),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.chofer')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'Entrega de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='GastoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=25)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.entregaventas')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'Gastos de entrega',
            },
        ),
        migrations.CreateModel(
            name='PagosVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('cancelado', models.BooleanField(default=True)),
                ('adicional_cc', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.mediodepago')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'Ingresos Ventas',
            },
        ),
        migrations.CreateModel(
            name='PagosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=25, null=True)),
                ('tomar_actualizado', models.BooleanField(default=True, verbose_name='tomar deuda actualizada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
                ('medio_de_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agenda.mediodepago')),
                ('pagos_ventas', models.ManyToManyField(blank=True, related_name='pagos_clientes', to='venta.pagosventas', verbose_name='Pagos adeudados')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'Cobro deudas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendedor')),
                ('nit', models.IntegerField(blank=True, null=True)),
                ('razon_cancelacion', models.CharField(blank=True, max_length=200, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('total_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.IntegerField(choices=[(0, 'creada'), (1, 'pagada'), (2, 'facturada'), (3, 'finalizada'), (4, 'cancelada'), (5, 'anulada')], default=0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.AddField(
            model_name='pagosventas',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=25)),
                ('cantidad_producto', models.DecimalField(decimal_places=2, default=1, max_digits=25)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('base', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.monedas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'verbose_name': 'detalle',
                'verbose_name_plural': 'Productos Vendidos',
            },
        ),
        migrations.CreateModel(
            name='VentaEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.entregaventas')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'Ventas a entregar',
            },
        ),
    ]
