# Generated by Django 4.1.5 on 2024-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_detalleventa_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='ganancias_estimadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
