# Generated by Django 5.0 on 2024-09-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_detalleventa_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='total',
        ),
    ]
