# Generated by Django 4.0.1 on 2024-12-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
        ('venta', '0005_remove_detalleventa_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventas',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
        migrations.AlterField(
            model_name='pagosclientes',
            name='pagos_ventas',
            field=models.ManyToManyField(blank=True, related_name='pagos_clientes', to='venta.PagosVentas', verbose_name='Pagos adeudados'),
        ),
    ]
