# Generated by Django 4.0.1 on 2024-12-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
        ('venta', '0006_pagosventas_caja_alter_pagosclientes_pagos_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosventas',
            name='caja',
        ),
        migrations.AddField(
            model_name='pagosclientes',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
    ]
