# Generated by Django 4.0.1 on 2024-12-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_configuracion_stock_negativo_ldp'),
        ('venta', '0007_remove_pagosventas_caja_pagosclientes_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosclientes',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.caja'),
        ),
    ]
