# Generated by Django 4.0.1 on 2024-12-14 14:42

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_pagosclientes_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'creada'), (3, 'finalizada'), (4, 'cancelada'), (5, 'anulada')], default=0),
        ),
    ]
