# Generated by Django 4.0.1 on 2024-12-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_mostrar_producto_tipo_recetaproducto'),
        ('venta', '0011_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosincluidosvendidos',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='productosincluidosvendidos',
            name='producto_compuesto_vendido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_incluidos', to='venta.productocompuestovendido'),
        ),
        migrations.AlterField(
            model_name='productosincluidosvendidos',
            name='receta_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_vendidos', to='producto.recetaproducto'),
        ),
        migrations.AlterField(
            model_name='productosincluidosvendidos',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], max_length=50, null=True),
        ),
    ]
