# Generated by Django 4.0.1 on 2024-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_alter_productosincluidosvendidos_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosincluidosvendidos',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
