# Generated by Django 4.0.1 on 2024-12-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_remove_configuracion_logo'),
        ('venta', '0013_alter_productosincluidosvendidos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosclientes',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente'),
        ),
    ]
