# Generated by Django 4.0.1 on 2024-12-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_alter_pagosclientes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
