# Generated by Django 5.0.11 on 2025-02-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_detalleventa_costo_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagosclientes',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'Pagos de clientes'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'Egresos'},
        ),
    ]
