# Generated by Django 5.0.11 on 2025-02-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0016_alter_pagosclientes_options_alter_venta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_fecha', models.DateTimeField(help_text='Seleccione la nueva fecha para la venta.')),
                ('confirmado', models.BooleanField(default=False, help_text='Indica si el ajuste ha sido confirmado.')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha en la que se confirmó el ajuste.', null=True)),
                ('venta', models.ForeignKey(help_text="Seleccione una venta que no esté en estado 'creada' ni 'anulada'.", on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
