# Generated by Django 5.0.11 on 2025-02-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_alter_configuracion_tiket_comandera'),
        ('ajustes', '0001_initial'),
        ('venta', '0016_alter_pagosclientes_options_alter_venta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustePagosClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nueva_fecha', models.DateField(help_text='Seleccione la nueva fecha para el pago.')),
                ('confirmado', models.BooleanField(default=False, help_text='Indica si el ajuste ha sido confirmado.')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha en la que se confirmó el ajuste.', null=True)),
                ('pago_cliente', models.ForeignKey(help_text='Seleccione el pago del cliente a ajustar (únicamente los que aún no se confirmaron).', on_delete=django.db.models.deletion.CASCADE, to='venta.pagosclientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAjustePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto a abonar con este medio.', max_digits=25)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ajustes.ajustepagosclientes')),
                ('medio_de_pago', models.ForeignKey(help_text='Seleccione el medio de pago a utilizar en el ajuste.', on_delete=django.db.models.deletion.CASCADE, to='agenda.mediodepago')),
            ],
        ),
        migrations.DeleteModel(
            name='AjusteVenta',
        ),
    ]
