# Generated by Django 5.0.11 on 2025-02-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_alter_configuracion_tiket_comandera'),
        ('ajustes', '0003_remove_detalleajustepago_ajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteventa',
            name='caja',
            field=models.ForeignKey(blank=True, help_text="Seleccione la caja que se asignará como vendedor (se asigna a 'nombre_factura').", null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.caja'),
        ),
        migrations.AlterField(
            model_name='ajustedetalleventa',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ajustepagosventa',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
